### ISSUE TITLE
Layout data preparation

### ISSUE THREAD

**Issue by ywyue** [OPEN-AIR-SUN/PQ-Transformer#3]
Hi, Thanks for your great work! I downloaded the sceneCAD layout dataset (http://kaldir.vc.in.tum.de/scannet_planes) and found it only contains 1149 scans (from scene0000 to scene0706). However, the official scannetv2 test split is from scene0707 to scene0806 (also indicated in your [meta data](https://github.com/OPEN-AIR-SUN/PQ-Transformer/blob/main/scannet/meta_data/scannetv2_test.txt)). So I am confused on which split do you test your model? Do you use official scannetv2 split for train/val/test? However, the sceneCAD layout dataset does not contain annotations for scenes in the test split. So I am very confused. Looking forward to your reply.

**Comment by cxx226** [comment]
We split scannet into [train set](https://github.com/OPEN-AIR-SUN/PQ-Transformer/blob/main/scannet/meta_data/scannetv2_train.txt) and [val set](https://github.com/OPEN-AIR-SUN/PQ-Transformer/blob/main/scannet/meta_data/scannetv2_val.txt) following [votenet](https://github.com/facebookresearch/votenet). For those scans which are not annotated by sceneCAD, we ignore them. So we actually use only 1149 scans in total.

**Comment by ywyue** [comment]
Thanks! Now it is clear.
