### ISSUE TITLE
Pre-trained Model for layout estimation only

### ISSUE THREAD

**Issue by ywyue** [OPEN-AIR-SUN/PQ-Transformer#4]
Hi thanks for the great work again! For layout estimation results on ScanNet, the paper lists the performance of the joint model and single model separately. Now I want to compare the performance on layout estimation with your model. For fair comparison, could you please provide the pretrained model only for layout estimation?

**Comment by ywyue** [comment]
I also have a question regarding your evaluation code for computing F1 score ([line 626 in ap_helper_pq.py](https://github.com/OPEN-AIR-SUN/PQ-Transformer/blob/74112f6d222fc04aae09d098736abfe11f9f8097/models/ap_helper_pq.py#L626)). It seems that only if the predicted number of floor corners is 4, you then count the tp. But there are many rooms whose number of floor corners is not necessarily 4 (Also shown in Fig. 8 of your paper). So I am very confused. Could you please explain a bit?

**Comment by Fromandto** [comment]
Xiaoxue says she will respond after the final exams.

**Comment by cxx226** [comment]
Sry, we don‘t have that pre-trained model at hand. For convenience, the code provided does only evaluate the results of the quads.

**Comment by ywyue** [comment]
Thanks for your reply!
